name: management_stock
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.0.3
  image_picker: ^1.2.0
  firebase_storage: ^13.0.3
  firebase_auth: ^6.1.1
  flutter_bloc: ^9.1.1
  firebase_core: ^4.2.0
  uuid: ^4.5.1
  intl: ^0.20.2
  csv: ^6.0.0
  printing: ^5.14.2
  path_provider: ^2.1.5
  pdf: ^3.11.3
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # ✅ شيل assets من هنا خالص
  # assets:
  #   - assets/fonts/
  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
