// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkC7SK54xsKcbtMumqXHb5GLZkwuGPsHI',
    appId: '1:151832949185:web:6be9978f72a9c10fd3bf40',
    messagingSenderId: '151832949185',
    projectId: 'stocks-9709e',
    authDomain: 'stocks-9709e.firebaseapp.com',
    storageBucket: 'stocks-9709e.firebasestorage.app',
    measurementId: 'G-WPBZBK2Z3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWsOMaCukihJXtAQjSySprC3NRBzUHwdM',
    appId: '1:151832949185:android:aba8959cfd5d3e94d3bf40',
    messagingSenderId: '151832949185',
    projectId: 'stocks-9709e',
    storageBucket: 'stocks-9709e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVAFoYhMyLK45g785li1n0xEAFuk5Rkbg',
    appId: '1:151832949185:ios:8eb47573dd8d50b1d3bf40',
    messagingSenderId: '151832949185',
    projectId: 'stocks-9709e',
    storageBucket: 'stocks-9709e.firebasestorage.app',
    iosBundleId: 'com.example.managementStock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVAFoYhMyLK45g785li1n0xEAFuk5Rkbg',
    appId: '1:151832949185:ios:8eb47573dd8d50b1d3bf40',
    messagingSenderId: '151832949185',
    projectId: 'stocks-9709e',
    storageBucket: 'stocks-9709e.firebasestorage.app',
    iosBundleId: 'com.example.managementStock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkC7SK54xsKcbtMumqXHb5GLZkwuGPsHI',
    appId: '1:151832949185:web:264d3769b8cb1988d3bf40',
    messagingSenderId: '151832949185',
    projectId: 'stocks-9709e',
    authDomain: 'stocks-9709e.firebaseapp.com',
    storageBucket: 'stocks-9709e.firebasestorage.app',
    measurementId: 'G-9EZ7ZTQSBP',
  );
}
